/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors');

module.exports = {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		colors: {
			transparent: 'transparent',
			current: 'currentColor',
			black: colors.black,
			white: colors.white,
			gray: colors.gray,
			accent: colors.violet,
			success: colors.lime,
			warning: colors.yellow,
			danger: colors.red,
			info: colors.sky,
		},
		fontFamily: {
			sans: [
				'InterVariable',
				'Noto Sans SC',
				'system-ui',
				'-apple-system',
				'BlinkMacSystemFont',
				'Segoe UI',
				'Roboto',
				'Helvetica Neue',
				'Arial',
				'Noto Sans',
				'sans-serif',
				'Apple Color Emoji',
				'Segoe UI Emoji',
				'Segoe UI Symbol',
				'Noto Color Emoji',
			],
			mono: [
				'Fira Mono',
				'Noto Sans SC',
				'ui-monospace',
				'SFMono-Regular',
				'Menlo',
				'Monaco',
				'Consolas',
				'Liberation Mono',
				'Courier New',
				'monospace',
			],
		},
		fontSize: {
			'dp-xs': ['1.5rem', { lineHeight: '2rem' }],
			'dp-sm': ['1.875rem', { lineHeight: '2.375rem' }],
			'dp-md': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em' }],
			'dp-lg': ['3rem', { lineHeight: '3.75rem', letterSpacing: '-0.02em' }],
			'dp-xl': ['3.75rem', { lineHeight: '4.5rem', letterSpacing: '-0.02em' }],
			'dp-2xl': ['4.5rem', { lineHeight: '5.625rem', letterSpacing: '-0.02em' }],
			xs: ['0.75rem', { lineHeight: '1.125rem' }],
			sm: ['0.875rem', { lineHeight: '1.25rem' }],
			md: ['1rem', { lineHeight: '1.5rem' }],
			lg: ['1.125rem', { lineHeight: '1.75rem' }],
			xl: ['1.25rem', { lineHeight: '1.875rem' }],
		},
		fontWeight: {
			regular: 400,
			medium: 500,
			semibold: 600,
			bold: 700,
		},
	},
	plugins: [require('./src/styles/index.cjs')],
};
