// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navbar: {
		guiluo: {
			/**
			 * 归​落​原
			 */
			text: string
			/**
			 * h​t​t​p​s​:​/​/​s​p​a​r​k​.​y​a​a​s​a​s​i​.​c​n​/
			 */
			link: string
		}
	}
	notfound: {
		/**
		 * 4​0​4​:​z​h
		 */
		title: string
	}
}

export type TranslationFunctions = {
	navbar: {
		guiluo: {
			/**
			 * 归落原
			 */
			text: () => LocalizedString
			/**
			 * https://spark.yaasasi.cn/
			 */
			link: () => LocalizedString
		}
	}
	notfound: {
		/**
		 * 404:zh
		 */
		title: () => LocalizedString
	}
}

export type Formatters = {}
